trigger:
- main

pool:
  name: Default  # 使用 Default 代理池

variables:
  buildConfiguration: 'Release'  # 正确地定义变量

steps:
# 使用 DotNetCoreCLI 任务
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(358b716c-117a-4491-a36e-bc557e2bdaa5)'
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'  # 使用变量
  displayName: 'dotnet build $(buildConfiguration)'

# 或者使用脚本直接构建
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
